apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -feat-ci
commonLabels:
  app.kubernetes.io/instance: feat-ci
  app.kubernetes.io/version: 1.0.0
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-ui
    path: ingress.yaml
