apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -feat-ci
commonLabels:
  app.kubernetes.io/instance: feat-ci
  app.kubernetes.io/version: 2.0.0
bases:
  - ../../base
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-ui
    path: ingress.yaml
