apiVersion: v1
kind: Service
metadata:
  name: banking-ui
  labels:
    app.kubernetes.io/name: banking-ui-service
    app.kubernetes.io/component: Service
    app.kubernetes.io/part-of: banking
spec:
  type: ClusterIP
  selector:
    app: banking-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-ui
  labels:
    app.kubernetes.io/name: banking-ui-deployment
    app.kubernetes.io/component: Frontend
    app.kubernetes.io/part-of: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-ui
  template:
    metadata:
      labels:
        app: banking-ui
        app.kubernetes.io/name: banking-ui-replicaset
        app.kubernetes.io/component: ReplicaSet
        app.kubernetes.io/part-of: banking-ui
    spec:
      containers:
        - name: banking-ui
          image: danielr1996/banking-ui
          imagePullPolicy: Always
          env:
            - name: GRAPHQL_API
              value: http://api.banking.danielr1996.de/graphql
          ports:
            - containerPort: 80
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: banking-ui
  labels:
    app.kubernetes.io/name: banking-ui-ingress
    app.kubernetes.io/component: Ingress
    app.kubernetes.io/part-of: banking
spec:
  rules:
    - host: banking.danielr1996.de
      http:
        paths:
          - backend:
              serviceName: banking-ui
              servicePort: 80
---
