apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-ui
spec:
  spec:
    containers:
      - name: banking-ui
        env:
          - name: GRAPHQL_API
            value: http://develop.api.banking.danielr1996.de/graphql
---
