apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -${INSTANCE}
commonLabels:
  app.kubernetes.io/instance: ${INSTANCE}
  app.kubernetes.io/version: 0.0.0
patchesStrategicMerge:
  - deployment.yaml
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: banking-ui
    path: ingress.yaml
