name: Build Pipeline

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@1.1.0
      - uses: danielr1996/docker-action-multitag@1.0.1
        with:
          imagename: danielr1996/banking-ui
          imagetags: |
            ${{ env.GITHUB_REF_SLUG }}
            ${{ env.GITHUB_SHA_SHORT }}
          dockeruser: ${{ secrets.DOCKER_USERNAME }}
          dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: ./.github/actions/kubectl-action
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -k deployment/overlays/${{ env.GITHUB_REF_SLUG }}
