name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build
        uses: ./.github/actions/docker-action
        with:
          imagename: danielr1996/banking-ui
          imagetag: ${{ extract_branch.outputs.branch }}
          dockeruser: ${{ secrets.DOCKER_USERNAME }}
          dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
#          args: apply -f deployment/deployment.yaml
          args: config view
